### ISSUE TITLE
FloodSub is not started

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-floodsub#50]
When running the pubsub tests (https://github.com/ipfs/js-ipfs/pull/108), I sometimes see the following error. 

```
Debug: internal, implementation, error
    AssertionError [ERR_ASSERTION]: FloodSub is not started
    at FloodSub.unsubscribe (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p-floodsub\src\index.js:324:5)
    at Object.unsubscribe (C:\Users\Owner\Documents\GitHub\js-ipfs\src\core\components\pubsub.js:41:12)
    at unsubscribe (C:\Users\Owner\Documents\GitHub\js-ipfs\src\http\api\resources\pubsub.js:36:19)
    at Object.internals.handler (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\podium\lib\index.js:287:26)
```

**Comment by richardschneider** [comment]
I think the issue is at https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L221.  The service is never started if there are no peers.

**Comment by richardschneider** [comment]
The above comment is wrong.  The stack trace indicates that `unsubscribe` is the problem. 

This [commit](https://github.com/libp2p/js-libp2p-floodsub/pull/51/commits/81d50febd80a2a6ba220f399eb7f0e0cea7269bf) fixes it.
